version: '3.9'

services:
  # RabbitMQ for messaging
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # MongoDB instances for services using Mongo
  mongo-user:
    image: mongo
    volumes:
      - mongo_user_data:/data/db

  mongo-movie:
    image: mongo
    volumes:
      - mongo_movie_data:/data/db

  mongo-playlist:
    image: mongo
    volumes:
      - mongo_playlist_data:/data/db

  mongo-analytics:
    image: mongo
    volumes:
      - mongo_analytics_data:/data/db

  # PostgreSQL instances for services using Postgres
  postgres-review:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: reviewdb
    volumes:
      - pg_review_data:/var/lib/postgresql/data

  postgres-history:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: historydb
    volumes:
      - pg_history_data:/var/lib/postgresql/data

  # User Service (MongoDB)
  user-service:
    build: ./user-service
    depends_on:
      - rabbitmq
      - mongo-user
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://mongo-user:27017/userdb
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4000:4000"

  # Movie Service (MongoDB)
  movie-service:
    build: ./movie-service
    depends_on:
      - rabbitmq
      - mongo-movie
    environment:
      - PORT=4001
      - MONGO_URL=mongodb://mongo-movie:27017/moviedb
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4001:4001"

  # Playlist Service (MongoDB)
  playlist-service:
    build: ./playlist-service
    depends_on:
      - rabbitmq
      - mongo-playlist
    environment:
      - PORT=4002
      - MONGO_URL=mongodb://mongo-playlist:27017/playlistdb
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4002:4002"

  # Review Service (PostgreSQL)
  review-service:
    build: ./review-service
    depends_on:
      - rabbitmq
      - postgres-review
    environment:
      - PORT=4003
      - POSTGRES_HOST=postgres-review
      - POSTGRES_DB=reviewdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4003:4003"

  # Analytics Service (MongoDB)
  analytics-service:
    build: ./analytics-service
    depends_on:
      - rabbitmq
      - mongo-analytics
    environment:
      - PORT=4004
      - MONGO_URL=mongodb://mongo-analytics:27017/analyticsdb
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4004:4004"

  # History Service (PostgreSQL)
  history-service:
    build: ./history-service
    depends_on:
      - rabbitmq
      - postgres-history
    environment:
      - PORT=4005
      - POSTGRES_HOST=postgres-history
      - POSTGRES_DB=historydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4005:4005"

volumes:
  mongo_user_data:
  mongo_movie_data:
  mongo_playlist_data:
  mongo_analytics_data:
  pg_review_data:
  pg_history_data:
